insert into categories (id, name) values (1, 'Cuidado Facial');
insert into categories (id, name) values (2, 'Cuidado Capilar');
insert into categories (id, name) values (3, 'Cuidado Corporal');
insert into categories (id, name) values (4, 'Sale');
insert into categories (id, name) values (5, 'Combos');
insert into categories (id, name) values (6, 'Accesorios');
insert into promo (id, name, value) values (1, 'Club La Nacion', 25);
insert into promo (id, name, value) values (2, 'Clarin 365', 20);
insert into promo (id, name, value) values (3, 'Club Personal', 25);
insert into promo (id, name, value) values (4, 'Santander Rio Women', 35);
insert into promo (id, name, value) values (5, 'Amex', 10);
insert into promo (id, name, value) values (6, 'Codigo de Descuento', 15);
insert into promo (id, name, value) values (7, 'Quiero Galicia', 30);
insert into promo (id, name, value) values (8, 'Tienda Supervielle', 20);
insert into promo (id, name, value) values (9, 'Club Claro', 20);
insert into role (id, name) values (1, 'Admin');
insert into role (id, name) values (2, 'User');
insert into role (id, name) values (3, 'Moderator');
insert into products (id, name, description, image, quantity, price, categoryId) values (1, 'BALSAMO LABIAL DE CACAO', 'nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes', 'bl1.jpg', 10, 170, 1);
insert into products (id, name, description, image, quantity, price, categoryId) values (2, 'EXFOLIANTE FACIAL DE CAFE Y AZUCAR', 'nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes', 'exf1.jpg', 15, 320, 1);
insert into products (id, name, description, image, quantity, price, categoryId) values (3, 'JABON CORPORAL DE ROSA MOSQUETA', 'nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes', 'j1.jpg', 8, 210, 3);
insert into products (id, name, description, image, quantity, price, categoryId) values (4, 'SHAMPOO SOLIDO FORTALECEDOR DE ORTIGA Y ROMERO', 'nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes', 'ss1.jpg', 14, 400, 2);
insert into products (id, name, description, image, quantity, price, categoryId) values (5, 'BALSAMO LABIAL DE CAFE', 'nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes', 'bl2.jpg', 5, 180, 1);
insert into products (id, name, description, image, quantity, price, categoryId) values (6, 'EXFOLIANTE CORPORAL DE LIMON Y ROMERO', 'nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes', 'exf2.jpg', 7, 290, 3);
insert into products (id, name, description, image, quantity, price, categoryId) values (7, 'JABON DETOX DE OLIVA Y CARBON', 'nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes', 'j4.jpg', 12, 230, 3);
insert into products (id, name, description, image, quantity, price, categoryId) values (8, 'SHAMPOO SÓLIDO REPARADOR KARITÉ', 'nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes', 'ss3.jpg', 17, 210, 2);
insert into users (id, firstName, lastName, date, phone, avatar, email, passwordHash, addressId, roleId) values (1, 'Lucas', 'Nicolas', '14/09/1992', '1122334455', 'profile-1616448718054.jpg', 'lucas@bhoomi.com', 'admin1234', NULL, 1);
insert into users (id, firstName, lastName, date, phone, avatar, email, passwordHash, addressId, roleId) values (2, 'Maria Laura', 'Stirparo', '30/01/1990', '1133445566', 'profile-1616448424565', 'laura@bhoomi.com', 'admin1234', NULL, 1);
insert into users (id, firstName, lastName, date, phone, avatar, email, passwordHash, addressId, roleId) values (3, 'Micaela', 'De Mello', '14/12/1995', '59896444111', 'profile-1616448787312', 'micaela@bhoomi.com', 'admin1234', NULL, 1);
insert into users (id, firstName, lastName, date, phone, avatar, email, passwordHash, addressId, roleId) values (4, 'Juan Roman', 'Riquelme', '24/06/1978', '1112121212', 'profile-1616448942734.jpg', 'riquelme@hotmail.com', 'user1234', NULL, 2);
insert into users (id, firstName, lastName, date, phone, avatar, email, passwordHash, addressId, roleId) values (5, 'Lady', 'Gaga', '28/03/1986', '1124536795', 'profile-1616448826372.jpg', 'gaga@yahoo.com', 'user1234', NULL, 2);
insert into users (id, firstName, lastName, date, phone, avatar, email, passwordHash, addressId, roleId) values (6, 'Taylor', 'Swift', '13/12/1989', '1185946542', 'profile-1616449066454.jpg', 'lataylor@gmail.com', 'user1234', NULL, 2);
insert into users (id, firstName, lastName, date, phone, avatar, email, passwordHash, addressId, roleId) values (7, 'Jorge', 'Bermudez', '18/06/1971', '1100120012', 'profile-1616448803674', 'elpatron@hotmail.com', 'user1234', NULL, 2);